(()=>{(()=>{function r(t,o){let e=document.getElementById("toast-container");if(!e)return;let n=document.createElement("div");n.className=`toast toast-${o}`;let a=o==="success"?'<svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z" fill="currentColor"/></svg>':'<svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z" fill="currentColor"/></svg>';n.innerHTML=`
    <div class="toast-icon">${a}</div>
    <div class="toast-message">${t}</div>
    <button class="toast-close" aria-label="Fechar">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="currentColor"/>
      </svg>
    </button>
  `;let s=n.querySelector(".toast-close");s.addEventListener("click",()=>{l(n)}),e.appendChild(n),s.focus(),setTimeout(()=>{l(n)},5e3)}function l(t){t.classList.add("hiding"),setTimeout(()=>{t.parentNode&&t.parentNode.removeChild(t)},300)}function i(){let t=document.querySelector(".header"),o=0;(window.pageYOffset||document.documentElement.scrollTop)>100?t.dataset.active="true":t.dataset.active="false",window.addEventListener("scroll",function(){let e=window.pageYOffset||document.documentElement.scrollTop;e>100?t.dataset.active="true":t.dataset.active="false",o=e})}function d(){let t=document.body,o=document.getElementById("nav-menu-button"),e=document.getElementById("nav-menu-drawer"),n=document.getElementById("nav-menu-drawer-backdrop");o.addEventListener("click",function(){t.classList.toggle("no-scroll");let a=e.dataset.active==="true";e.dataset.active=a?"false":"true"}),n.addEventListener("click",function(){t.classList.toggle("no-scroll");let a=e.dataset.active==="true";e.dataset.active=a?"false":"true"})}function c(){let t=document.getElementById("nav-dropdown-toggle-mobile");t&&t.addEventListener("click",function(){let o=document.getElementById("nav-dropdown-mobile");if(o){o.classList.toggle("active");let e=o.querySelectorAll(".nav-dropdown-item");o.classList.contains("active")?e.forEach(n=>{n.setAttribute("tabindex","0")}):e.forEach(n=>{n.setAttribute("tabindex","-1")})}})}document.addEventListener("DOMContentLoaded",function(){i(),d(),c()})})();})();
