(()=>{function r(e,n){let o=document.getElementById("toast-container");if(!o)return;let t=document.createElement("div");t.className=`toast toast-${n}`;let s=n==="success"?'<svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z" fill="currentColor"/></svg>':'<svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z" fill="currentColor"/></svg>';t.innerHTML=`
    <div class="toast-icon">${s}</div>
    <div class="toast-message">${e}</div>
    <button class="toast-close" aria-label="Fechar">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="currentColor"/>
      </svg>
    </button>
  `;let a=t.querySelector(".toast-close");a.addEventListener("click",()=>{c(t)}),o.appendChild(t),a.focus(),setTimeout(()=>{c(t)},5e3)}function c(e){e.classList.add("hiding"),setTimeout(()=>{e.parentNode&&e.parentNode.removeChild(e)},300)}function d(){let e=document.querySelector(".header"),n=0;(window.pageYOffset||document.documentElement.scrollTop)>100?e.dataset.active="true":e.dataset.active="false",window.addEventListener("scroll",function(){let t=window.pageYOffset||document.documentElement.scrollTop;t>100?e.dataset.active="true":e.dataset.active="false",n=t})}function l(){let e=document.body,n=document.getElementById("nav-menu-button"),o=document.getElementById("nav-menu-drawer"),t=document.getElementById("nav-menu-drawer-backdrop");n.addEventListener("click",function(){e.classList.toggle("no-scroll");let s=o.dataset.active==="true";o.dataset.active=s?"false":"true"}),t.addEventListener("click",function(){e.classList.toggle("no-scroll");let s=o.dataset.active==="true";o.dataset.active=s?"false":"true"})}function i(){let e=document.getElementById("nav-dropdown-toggle-mobile");e&&e.addEventListener("click",function(){let n=document.getElementById("nav-dropdown-mobile");if(n){n.classList.toggle("active");let o=n.querySelectorAll(".nav-dropdown-item");n.classList.contains("active")?o.forEach(t=>{t.setAttribute("tabindex","0")}):o.forEach(t=>{t.setAttribute("tabindex","-1")})}})}document.addEventListener("DOMContentLoaded",function(){d(),l(),i()});})();
